/**
 * Ed25519 signing for certification artifacts.
 * Private key: CERT_SIGNING_PRIVATE_KEY (base64 of PEM or DER).
 * Public key: CERT_SIGNING_PUBLIC_KEY (base64 of PEM or DER).
 * In NODE_ENV=production: keys required; startup validation blocks if missing.
 * In development: keys auto-generated on first use when not set (demos always produce real signatures).
 */

import { createPrivateKey, createPublicKey, generateKeyPairSync, sign, verify } from 'crypto';
import type { KeyObject } from 'crypto';
import { getMode } from './runtime_mode.js';

const ALG = 'ed25519';

let _privateKey: KeyObject | null = null;
let _publicKey: KeyObject | null = null;
let _publicKeyB64: string = '';
let _keysLoaded = false;
let _autoGenerated = false;

/** Reset cached keys (for tests). */
export function resetSigningKeysCache(): void {
  _keysLoaded = false;
  _privateKey = null;
  _publicKey = null;
  _publicKeyB64 = '';
  _autoGenerated = false;
}

function autoGenerateKeys(): void {
  const { privateKey, publicKey } = generateKeyPairSync('ed25519', {
    privateKeyEncoding: { format: 'der', type: 'pkcs8' },
    publicKeyEncoding: { format: 'der', type: 'spki' },
  });
  const privBuf = privateKey as Buffer;
  const pubBuf = publicKey as Buffer;
  _privateKey = createPrivateKey({ key: privBuf, format: 'der', type: 'pkcs8' });
  _publicKey = createPublicKey({ key: pubBuf, format: 'der', type: 'spki' });
  _publicKeyB64 = pubBuf.toString('base64');
  _autoGenerated = true;
  // eslint-disable-next-line no-console
  console.warn(
    '[CERT_SIGNING] Using auto-generated Ed25519 keys. Set CERT_SIGNING_PRIVATE_KEY and CERT_SIGNING_PUBLIC_KEY in production.'
  );
}

function loadKeys(): void {
  if (_keysLoaded) return;
  _keysLoaded = true;
  const privB64 = process.env.CERT_SIGNING_PRIVATE_KEY?.trim();
  const pubB64 = process.env.CERT_SIGNING_PUBLIC_KEY?.trim();
  if (privB64 && pubB64) {
    try {
      const privBuf = Buffer.from(privB64, 'base64');
      const pubBuf = Buffer.from(pubB64, 'base64');
      const privStr = privBuf.toString('utf8');
      const pubStr = pubBuf.toString('utf8');
      _privateKey = privStr.startsWith('-----')
        ? createPrivateKey(privStr)
        : createPrivateKey({ key: privBuf, format: 'der', type: 'pkcs8' });
      _publicKey = pubStr.startsWith('-----')
        ? createPublicKey(pubStr)
        : createPublicKey({ key: pubBuf, format: 'der', type: 'spki' });
      _publicKeyB64 = pubB64;
    } catch {
      _privateKey = null;
      _publicKey = null;
      _publicKeyB64 = '';
    }
  }
  if (!_privateKey || !_publicKey) {
    if (process.env.NODE_ENV !== 'production') {
      autoGenerateKeys();
    }
  }
}

export function isSigningConfigured(): boolean {
  loadKeys();
  return _privateKey != null && _publicKey != null;
}

export function getPublicKeyB64(): string {
  loadKeys();
  return _publicKeyB64;
}

export function assertSigningKeysInStrictMode(): void {
  loadKeys();
  const mode = getMode();
  if (mode === 'dev') return;
  if (!_privateKey || !_publicKey) {
    throw new Error(
      '[FATAL] MODE=' + mode + ': Ed25519 signing keys required. Run: npx tsx src/crypto/keygen.ts to generate.'
    );
  }
}

export interface SignResult {
  signatureB64: string;
  publicKeyB64: string;
  alg: string;
  signed: boolean;
}

/** Sign artifact hash (hex). Returns signed=false when keys not configured (dev). */
export function signArtifactHash(hashHex: string): SignResult {
  loadKeys();
  if (!_privateKey || !_publicKey) {
    return {
      signatureB64: '',
      publicKeyB64: '',
      alg: ALG,
      signed: false,
    };
  }
  const hashBuf = Buffer.from(hashHex, 'hex');
  const sig = sign(null, hashBuf, _privateKey);
  return {
    signatureB64: sig.toString('base64'),
    publicKeyB64: _publicKeyB64,
    alg: ALG,
    signed: true,
  };
}

/** Verify signature over artifact hash. Returns false when signature invalid. */
export function verifyArtifactHash(
  hashHex: string,
  signatureB64: string,
  publicKeyB64: string
): boolean {
  if (!signatureB64 || !publicKeyB64) return false;
  try {
    const hashBuf = Buffer.from(hashHex, 'hex');
    const sigBuf = Buffer.from(signatureB64, 'base64');
    const pubBuf = Buffer.from(publicKeyB64, 'base64');
    const pubStr = pubBuf.toString('utf8');
    const pubKey = pubStr.startsWith('-----')
      ? createPublicKey(pubStr)
      : createPublicKey({ key: pubBuf, format: 'der', type: 'spki' });
    return verify(null, hashBuf, pubKey, sigBuf);
  } catch {
    return false;
  }
}
