/**
 * Justification chat: RAG (FASB/IFRS handbooks), IRAC format, [Source] citation, Export Audit Defense PDF.
 * Analysis and conclusion are generated by Claude 3.5 Sonnet, citing FASB/IFRS codifications from RAG chunks.
 * Durable justifications: when pool/tenantId provided, stored in tenant_justifications; else in-memory (dev only).
 */

import type { Pool } from 'pg';
import { generateText } from '../llm/provider.js';
import { enterAdvisoryContext, exitAdvisoryContext } from '../lib/ai_boundary.js';
import { assertNoNumericAmountsInAgentOutput } from '../llm/guardrails.js';
import type {
  HandbookChunk,
  IRACJustification,
  JustificationResponse,
  JustificationRAGStore,
  RAGResult,
  StoredJustification,
} from '../types/justification.js';
// QUARANTINED — rag_handbook not in MVP architecture
// import { getDefaultRAGStore } from './rag_handbook.js';
import { isDbConfigured } from '../db/index.js';
import { disallowMemoryStoreInProduction } from '../lib/env.js';
import * as justificationsRepo from '../db/repositories/tenant_justifications_repository.js';
import type { JustificationRelatedType, CreatedByType } from '../db/repositories/tenant_justifications_repository.js';
import { runJustifier, hashJustifierInputs, type JustifierRelatedType } from '../ai/ai_orchestrator.js';

export interface CreateJustificationFromAIParams {
  tenantId: string;
  pool: Pool;
  periodLabel: string;
  relatedType: JustificationRelatedType;
  relatedId: string;
  memo_markdown: string;
  irac_json?: { issue: string; rule: string; analysis: string; conclusion: string };
  rule_ids?: string[];
  prompt_version: string;
  model?: string;
  inputs_hash: string;
  /** When 'draft', justification requires human review before association with the JE. */
  status?: 'draft' | 'approved';
}

// --- In-memory store (fallback when no DB/tenant; production disallows) ---
const justificationStore: StoredJustification[] = [];

// --- IRAC formatting ---

const SOURCE_TAG_PREFIX = '[Source: ';
const SOURCE_TAG_SUFFIX = ']';

/**
 * Format a justification in Issue-Rule-Analysis-Conclusion (IRAC) legal format.
 * Every response includes a [Source] tag pointing to the specific section of the accounting code.
 */
export function formatIRAC(
  issue: string,
  rule: string,
  analysis: string,
  conclusion: string,
  sourceCitation: string
): IRACJustification & { sourceTag: string } {
  const sourceTag = sourceCitation.startsWith('[') ? sourceCitation : `${SOURCE_TAG_PREFIX}${sourceCitation}${SOURCE_TAG_SUFFIX}`;
  return {
    issue,
    rule,
    analysis,
    conclusion,
    source: sourceCitation,
    sourceTag,
  };
}

/**
 * Build full formatted text: IRAC sections plus [Source] at end.
 */
export function formatJustificationText(irac: IRACJustification, sourceTag: string): string {
  const lines = [
    '**Issue**',
    irac.issue,
    '',
    '**Rule**',
    irac.rule,
    '',
    '**Analysis**',
    irac.analysis,
    '',
    '**Conclusion**',
    irac.conclusion,
    '',
    sourceTag,
  ];
  return lines.join('\n');
}

// --- LLM-generated analysis and conclusion (Claude 3.5 Sonnet) ---

const IRAC_LLM_MODEL = 'claude-sonnet-4-5-20250929';

async function generateIRACAnalysisAndConclusion(
  issue: string,
  ruleText: string,
  question: string,
  chunks: HandbookChunk[]
): Promise<{ analysis: string; conclusion: string }> {
  const fallbackConclusion = `Therefore, the accounting treatment is supported by ${chunks[0]?.framework ?? 'FASB'} ${chunks[0]?.citation ?? 'FASB ASC (General)'}.`;
  if (!process.env.ANTHROPIC_API_KEY && !process.env.OPENAI_API_KEY && !process.env.MISTRAL_API_KEY) {
    return {
      analysis: `Applying the foregoing guidance to the facts: ${question.trim().slice(0, 200)}. The treatment is consistent with the authoritative literature cited.`,
      conclusion: fallbackConclusion,
    };
  }

  const citationsBlock = chunks.length
    ? chunks
        .map((c) => `- ${c.framework} ${c.citation}${c.section ? ` (${c.section})` : ''}: ${c.text}`)
        .join('\n')
    : 'No specific authority chunks. Apply GAAP/IFRS as appropriate.';

  const system = `You are an expert in GAAP/IFRS. Write IRAC-style Analysis and Conclusion for an accounting justification. 
  Cite the specific FASB ASC or IFRS codifications from the provided authority chunks. Use the exact citation strings (e.g. "FASB ASC 606-10-25-1", "IAS 1.54") when referencing the literature.
  Output exactly two short paragraphs: first "Analysis:", then "Conclusion:". Do not include section headers in the text; just the paragraphs.`;
  const prompt = `Issue: ${issue}\n\nRule (from authority): ${ruleText}\n\nRelevant authority chunks:\n${citationsBlock}\n\nUser question / facts: ${question.slice(0, 500)}\n\nWrite Analysis (apply the rule to the facts; cite the codifications above) and Conclusion (state whether the treatment is supported and by which citation).`;

  enterAdvisoryContext();
  try {
    const text = await generateText({
      model: IRAC_LLM_MODEL,
      maxTokens: 1024,
      system,
      prompt,
    });

    // Apply numeric guardrail on raw text (IRAC narrative output)
    assertNoNumericAmountsInAgentOutput({ text }, 'justification_service_irac');

    let analysis = text;
    let conclusion = '';
    const conclusionMatch = text.match(/\bConclusion:?\s*([\s\S]*)/i);
    if (conclusionMatch) {
      conclusion = conclusionMatch[1].trim();
      analysis = text.slice(0, text.indexOf(conclusionMatch[0])).replace(/Analysis:?\s*/i, '').trim();
    }
    if (!conclusion) {
      const lastPara = text.split(/\n\n+/).pop() ?? text;
      conclusion = lastPara.trim();
      analysis = text.slice(0, text.lastIndexOf(lastPara)).replace(/Analysis:?\s*/i, '').trim();
    }
    if (!analysis) analysis = text;
    if (!conclusion) conclusion = fallbackConclusion;

    return { analysis, conclusion };
  } finally {
    exitAdvisoryContext();
  }
}

// --- RAG-backed justification ---

export interface JustifyOptions {
  ragStore?: JustificationRAGStore;
  framework?: 'FASB' | 'IFRS';
}

/**
 * Produce a justification using RAG (FASB/IFRS handbook). Returns IRAC + [Source] citation.
 * Analysis and conclusion are generated by Claude 3.5 Sonnet, citing the specific codifications from RAG chunks.
 */
export async function justifyWithRAG(
  question: string,
  options?: JustifyOptions
): Promise<JustificationResponse> {
  // QUARANTINED — rag_handbook not in MVP architecture
  // const store = options?.ragStore ?? getDefaultRAGStore();
  const store = options?.ragStore ?? { query: async (q: string) => ({ chunks: [], query: q }) };
  const rag: RAGResult = await store.query(question, {
    topK: 3,
    framework: options?.framework,
  });
  const chunks = rag.chunks;
  const chunk = chunks[0];
  const citation = chunk ? chunk.citation : 'FASB ASC (General)';
  const ruleText = chunk ? chunk.text : 'Relevant GAAP or IFRS applies as determined by management and auditors.';

  const issue = normalizeIssue(question);
  const rule = ruleText;

  const { analysis, conclusion } = await generateIRACAnalysisAndConclusion(issue, rule, question, chunks);

  const sourceTag = `${SOURCE_TAG_PREFIX}${chunk?.framework ?? 'FASB'} ${citation}${SOURCE_TAG_SUFFIX}`;

  const irac: IRACJustification = {
    issue,
    rule,
    analysis,
    conclusion,
    source: `${chunk?.framework ?? 'FASB'} ${citation}`,
  };

  const formatted = formatJustificationText(irac, sourceTag);

  const out: JustificationResponse = {
    irac,
    sourceTag,
    formatted,
  };

  storeJustification(question, out);
  return out;
}

function normalizeIssue(q: string): string {
  const t = q.trim();
  if (t.length === 0) return 'Whether the accounting treatment is appropriate under GAAP/IFRS.';
  if (t.length > 300) return t.slice(0, 297) + '...';
  return t;
}

function storeJustification(question: string, response: JustificationResponse): void {
  justificationStore.push({
    id: `j-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
    question,
    response,
    timestamp: new Date().toISOString(),
  });
}

// --- Durable justification (DB-backed when pool/tenantId provided) ---

export interface CreateJustificationParams {
  tenantId: string;
  pool: Pool;
  periodLabel: string;
  relatedType: JustificationRelatedType;
  relatedId: string;
  createdBy?: string;
  createdByType?: CreatedByType;
  /** IRAC + sourceTag + formatted (from JustificationResponse) */
  response?: JustificationResponse;
  /** Plain memo when no full IRAC (e.g. HITL approval reason) */
  memoMarkdown?: string;
  promptVersion?: string;
  model?: string;
  inputsHash?: string;
}

/**
 * Create a durable justification row linked to hitl_staging, close_adjustment, journal_entry, export, or ingest.
 * Call when HITL item is approved, adjustment is approved/posted, or JE is posted.
 */
export async function createJustification(params: CreateJustificationParams): Promise<{ id: string; createdAt: string }> {
  const { tenantId, pool, periodLabel, relatedType, relatedId, createdBy, createdByType = 'user', response, memoMarkdown, promptVersion, model, inputsHash } = params;
  if (!isDbConfigured() || !pool) {
    disallowMemoryStoreInProduction({ storeName: 'justification (create)', hasDurableContext: false });
    const id = `j-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
    const timestamp = new Date().toISOString();
    justificationStore.push({
      id,
      question: memoMarkdown ?? `${relatedType}: ${relatedId}`,
      response: response ?? {
        irac: { issue: memoMarkdown ?? relatedId, rule: '', analysis: '', conclusion: '', source: '' },
        sourceTag: '',
        formatted: memoMarkdown ?? relatedId,
      },
      timestamp,
      periodStart: periodLabel,
      periodEnd: periodLabel,
    });
    return { id, createdAt: timestamp };
  }
  const iracJson = response
    ? { irac: response.irac, sourceTag: response.sourceTag, formatted: response.formatted }
    : memoMarkdown
      ? {
          irac: { issue: memoMarkdown, rule: '', analysis: '', conclusion: memoMarkdown, source: '' },
          sourceTag: '',
          formatted: memoMarkdown,
        }
      : undefined;
  return justificationsRepo.createJustification(pool, {
    tenantId,
    periodLabel,
    relatedType,
    relatedId,
    createdBy,
    createdByType,
    iracJson,
    memoMarkdown: memoMarkdown ?? (response ? response.formatted.slice(0, 2000) : undefined),
    promptVersion,
    model,
    inputsHash,
  });
}

/**
 * Persist AI-generated justification (Justifier pillar) to tenant_justifications.
 * Call after runJustifier; use placeholder memo when AI fails (ok: false).
 */
export async function createJustificationFromAI(
  params: CreateJustificationFromAIParams
): Promise<{ id: string; createdAt: string }> {
  const {
    tenantId,
    pool,
    periodLabel,
    relatedType,
    relatedId,
    memo_markdown,
    irac_json,
    prompt_version,
    model,
    inputs_hash,
  } = params;
  if (!isDbConfigured() || !pool) {
    disallowMemoryStoreInProduction({ storeName: 'justification (createFromAI)', hasDurableContext: false });
    const id = `j-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
    return { id, createdAt: new Date().toISOString() };
  }
  const iracJson = irac_json
    ? { irac: { ...irac_json, source: '' }, sourceTag: '', formatted: memo_markdown }
    : { irac: { issue: memo_markdown, rule: '', analysis: '', conclusion: memo_markdown, source: '' }, sourceTag: '', formatted: memo_markdown };
  return justificationsRepo.createJustification(pool, {
    tenantId,
    periodLabel,
    relatedType,
    relatedId,
    createdBy: 'justifier',
    createdByType: 'agent',
    iracJson,
    memoMarkdown: memo_markdown,
    promptVersion: prompt_version,
    model: model ?? undefined,
    inputsHash: inputs_hash,
  });
}

/**
 * Ensure a justification row exists for a posted JE. If none, create minimal memo (scope: auto-generate required minimum).
 * Call after postJE so every posted JE has a justification id for the binder.
 */
export async function ensureJustificationForPostedJE(
  pool: Pool,
  tenantId: string,
  jeId: string,
  periodLabel: string,
  approvedBy?: string
): Promise<{ id: string; createdAt: string } | null> {
  if (!isDbConfigured() || !pool) return null;
  const existing = await justificationsRepo.getJustificationByRelated(pool, tenantId, 'journal_entry', jeId);
  if (existing) return { id: existing.id, createdAt: existing.created_at };
  const memo = `Journal entry posted. Approved by ${approvedBy ?? 'unknown'}.`;
  return createJustification({
    tenantId,
    pool,
    periodLabel,
    relatedType: 'journal_entry',
    relatedId: jeId,
    createdBy: approvedBy,
    createdByType: 'user',
    memoMarkdown: memo,
  });
}

/** Map DB row to StoredJustification for binder/export. */
function rowToStoredJustification(row: justificationsRepo.JustificationRow): StoredJustification {
  const iracPayload = row.irac_json as { irac?: IRACJustification; sourceTag?: string; formatted?: string } | null;
  const irac = iracPayload?.irac ?? { issue: row.memo_markdown ?? `${row.related_type}: ${row.related_id}`, rule: '', analysis: '', conclusion: '', source: '' };
  const sourceTag = iracPayload?.sourceTag ?? '';
  const formatted = iracPayload?.formatted ?? row.memo_markdown ?? '';
  return {
    id: row.id,
    question: row.memo_markdown ?? `${row.related_type}: ${row.related_id}`,
    response: { irac, sourceTag, formatted },
    timestamp: row.created_at,
    periodStart: row.period_label,
    periodEnd: row.period_label,
  };
}

// --- Export Audit Defense ---

export interface ExportAuditDefenseOptions {
  periodStart: string;
  periodEnd: string;
  title?: string;
  entityName?: string;
  tenantId?: string;
  pool?: Pool | null;
}

/**
 * Get all justifications in a period for Export Audit Defense.
 * When tenantId and pool are provided, reads from tenant_justifications; else in-memory (dev only).
 */
export async function getJustificationsForPeriod(
  periodStart: string,
  periodEnd: string,
  tenantId?: string,
  pool?: Pool | null
): Promise<StoredJustification[]> {
  if (isDbConfigured() && pool && tenantId) {
    const rows = await justificationsRepo.listJustificationsForPeriodRange(pool, tenantId, periodStart, periodEnd);
    return rows.map(rowToStoredJustification);
  }
  disallowMemoryStoreInProduction({ storeName: 'justification (list)', hasDurableContext: false });
  const start = new Date(periodStart).getTime();
  const end = new Date(periodEnd).getTime();
  return justificationStore.filter((j) => {
    const t = new Date(j.timestamp).getTime();
    return t >= start && t <= end;
  });
}

/**
 * Build Audit Defense summary (HTML) for a period. Used for PDF export.
 */
export async function buildAuditDefenseSummary(options: ExportAuditDefenseOptions): Promise<{
  html: string;
  justifications: StoredJustification[];
}> {
  const { periodStart, periodEnd, title = 'Audit Defense — Justifications', entityName = 'Entity', tenantId, pool } = options;
  const justifications = await getJustificationsForPeriod(periodStart, periodEnd, tenantId, pool);

  const sections = justifications
    .map(
      (j: StoredJustification, i: number) => `
    <div class="justification" style="margin-bottom: 2rem; page-break-inside: avoid;">
      <h3 style="font-size: 1rem; margin-bottom: 0.5rem;">${i + 1}. ${escapeHtml(j.question.slice(0, 100))}${j.question.length > 100 ? '...' : ''}</h3>
      <p style="font-size: 0.75rem; color: #666;">${escapeHtml(j.timestamp)}</p>
      <div style="margin-left: 0.5rem;">
        <p><strong>Issue:</strong> ${escapeHtml(j.response.irac.issue)}</p>
        <p><strong>Rule:</strong> ${escapeHtml(j.response.irac.rule)}</p>
        <p><strong>Analysis:</strong> ${escapeHtml(j.response.irac.analysis)}</p>
        <p><strong>Conclusion:</strong> ${escapeHtml(j.response.irac.conclusion)}</p>
        <p><strong>Citation:</strong> ${escapeHtml(j.response.sourceTag)}</p>
      </div>
    </div>
  `
    )
    .join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: Georgia, serif; font-size: 11pt; line-height: 1.5; max-width: 800px; margin: 2rem auto; padding: 0 1rem; }
    h1 { font-size: 1.5rem; border-bottom: 1px solid #333; padding-bottom: 0.5rem; }
    h2 { font-size: 1.2rem; margin-top: 1.5rem; }
    .meta { color: #666; font-size: 0.9rem; margin-bottom: 1.5rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">
    <p><strong>Entity:</strong> ${escapeHtml(entityName)}</p>
    <p><strong>Period:</strong> ${escapeHtml(periodStart)} to ${escapeHtml(periodEnd)}</p>
    <p><strong>Report generated:</strong> ${new Date().toISOString()}</p>
  </div>
  <h2>Justifications (IRAC)</h2>
  ${sections || '<p>No justifications recorded for this period.</p>'}
</body>
</html>`;

  return { html, justifications };
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Export Audit Defense: generate PDF buffer for justifications in a period.
 * Uses dynamic import of pdf-lib or returns HTML for client-side PDF; see route for actual PDF generation.
 */
export async function exportAuditDefensePDF(options: ExportAuditDefenseOptions): Promise<Buffer> {
  const { html } = await buildAuditDefenseSummary(options);
  // Use a simple PDF library. pdf-lib doesn't do HTML; we use puppeteer or jsPDF in browser, or a Node HTML-to-PDF.
  // For Node without puppeteer: return HTML as fallback and let route set Content-Type or use pdf-lib to build simple PDF.
  try {
    const { createPdfFromHtml } = await import('./pdf_export.js');
    return await createPdfFromHtml(html);
  } catch {
    // Fallback: return HTML as buffer so caller can serve as HTML or use external service for PDF
    return Buffer.from(html, 'utf-8');
  }
}

/**
 * Register a justification with period for audit defense (call from chat).
 */
export function registerJustificationForPeriod(
  question: string,
  response: JustificationResponse,
  periodStart?: string,
  periodEnd?: string
): void {
  justificationStore.push({
    id: `j-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
    question,
    response,
    timestamp: new Date().toISOString(),
    periodStart,
    periodEnd,
  });
}

// --- Orchestrator-based justification (Justifier pillar) ---

export interface JustifyWithOrchestratorParams {
  pool: Pool;
  tenantId: string;
  periodLabel: string;
  relatedType: JustifierRelatedType;
  relatedId: string;
  facts: Record<string, unknown>;
}

/**
 * Generate an IRAC justification via the AI orchestrator's Justifier pillar,
 * then persist the result to tenant_justifications. Fail-open: returns a
 * placeholder memo if AI fails. Always persists regardless of AI success.
 */
export async function justifyWithOrchestrator(
  params: JustifyWithOrchestratorParams
): Promise<{ id: string; createdAt: string; ok: boolean; memo_markdown: string }> {
  const { pool, tenantId, periodLabel, relatedType, relatedId, facts } = params;
  const inputsHash = hashJustifierInputs(facts, 'justifier_v1.0.0');

  const result = await runJustifier({
    pool,
    tenantId,
    periodLabel,
    relatedType,
    relatedId,
    facts,
  });

  const persisted = await createJustificationFromAI({
    tenantId,
    pool,
    periodLabel,
    relatedType,
    relatedId,
    memo_markdown: result.memo_markdown,
    irac_json: result.irac_json,
    rule_ids: result.rule_ids,
    prompt_version: result.prompt_version,
    model: process.env.AI_MODEL,
    inputs_hash: inputsHash,
  });

  return {
    id: persisted.id,
    createdAt: persisted.createdAt,
    ok: result.ok,
    memo_markdown: result.memo_markdown,
  };
}

/**
 * Create a "Bridge Adjustment Justification" memo for audit: CPA Brain adjustment executed via deterministic engine.
 * Cites the specific ASC/IFRS paragraph and explains why the math (deterministic output) is correct.
 * Call after every successful executeAgentRecommendation so the adjustment is accompanied by a justification.
 */
export function createBridgeAdjustmentJustification(
  standardKey: string,
  standardName: string,
  params: Record<string, unknown>,
  resultSummary: string
): JustificationResponse {
  const citations: Record<string, string> = {
    Lease: 'FASB ASC 842-20-25-1; IFRS 16.22',
    Revenue: 'FASB ASC 606-10-25-1; IFRS 15.31',
    FixedAsset: 'FASB ASC 360-10-35-4; IAS 16.50',
    Tax: 'FASB ASC 740-10-25-2; IAS 12.24',
  };
  const citation = citations[standardKey] ?? 'FASB ASC (General)';
  const issue = `Whether the ${standardName} deterministic output is correct given the provided inputs.`;
  const rule = `Under ${citation}, the accounting treatment is determined by the stated inputs; the deterministic engine computes the result in accordance with the standard.`;
  const analysis = `Inputs: ${JSON.stringify(params).slice(0, 300)}. Deterministic output: ${resultSummary.slice(0, 200)}.`;
  const conclusion = `The adjustment is supported by ${citation}. The math (deterministic output) is correct for the given inputs.`;
  const sourceTag = `[Source: ${citation}]`;
  const irac: IRACJustification = { issue, rule, analysis, conclusion, source: citation };
  const formatted = formatJustificationText(irac, sourceTag);
  const response: JustificationResponse = { irac, sourceTag, formatted };
  registerJustificationForPeriod(`Bridge: ${standardName}`, response);
  return response;
}

/**
 * Create an "Ingestion Integrity Memo" for audit: trial balance ingested and validated; debits equal credits; balance sheet equation satisfied.
 * Call immediately after every successful TB ingest so audit routes (e.g. Export Audit Defense) include it.
 */
export function createIngestionIntegrityMemo(
  periodLabel: string,
  summary: string
): void {
  const issue = 'Whether the trial balance and balance sheet are mathematically correct after ingestion.';
  const rule = 'ASC 210-10-45, IAS 1.49: Assets = Liabilities + Equity. Trial balance: Sum(Debits) = Sum(Credits).';
  const analysis = summary || 'Trial balance ingested; column mapping applied; debits equal credits; balance sheet equation satisfied.';
  const conclusion = 'Ingestion integrity confirmed. Data is suitable for financial statement preparation and audit.';
  const sourceTag = '[Source: FASB ASC 210-10-45; IAS 1.49]';
  const irac: IRACJustification = { issue, rule, analysis, conclusion, source: 'FASB ASC 210-10-45; IAS 1.49' };
  const formatted = formatJustificationText(irac, sourceTag);
  const response: JustificationResponse = { irac, sourceTag, formatted };
  const periodStart = periodLabel.startsWith('ingest-') ? new Date().toISOString().slice(0, 10) : `${periodLabel.slice(0, 4)}-01-01`;
  const periodEnd = periodLabel.startsWith('ingest-') ? new Date().toISOString().slice(0, 10) : `${periodLabel.slice(0, 4)}-12-31`;
  registerJustificationForPeriod('Ingestion Integrity Memo', response, periodStart, periodEnd);
}
