/**
 * Justification chat: RAG (FASB/IFRS handbooks), IRAC format, [Source] citation, Export Audit Defense PDF.
 * Analysis and conclusion are generated by Claude 3.5 Sonnet, citing FASB/IFRS codifications from RAG chunks.
 */

import { generateText } from '../llm/provider.js';
import type {
  HandbookChunk,
  IRACJustification,
  JustificationResponse,
  JustificationRAGStore,
  RAGResult,
  StoredJustification,
} from '../types/justification.js';
import { getDefaultRAGStore } from './rag_handbook.js';

// --- In-memory store of justifications for a period (for Export Audit Defense) ---
const justificationStore: StoredJustification[] = [];

// --- IRAC formatting ---

const SOURCE_TAG_PREFIX = '[Source: ';
const SOURCE_TAG_SUFFIX = ']';

/**
 * Format a justification in Issue-Rule-Analysis-Conclusion (IRAC) legal format.
 * Every response includes a [Source] tag pointing to the specific section of the accounting code.
 */
export function formatIRAC(
  issue: string,
  rule: string,
  analysis: string,
  conclusion: string,
  sourceCitation: string
): IRACJustification & { sourceTag: string } {
  const sourceTag = sourceCitation.startsWith('[') ? sourceCitation : `${SOURCE_TAG_PREFIX}${sourceCitation}${SOURCE_TAG_SUFFIX}`;
  return {
    issue,
    rule,
    analysis,
    conclusion,
    source: sourceCitation,
    sourceTag,
  };
}

/**
 * Build full formatted text: IRAC sections plus [Source] at end.
 */
export function formatJustificationText(irac: IRACJustification, sourceTag: string): string {
  const lines = [
    '**Issue**',
    irac.issue,
    '',
    '**Rule**',
    irac.rule,
    '',
    '**Analysis**',
    irac.analysis,
    '',
    '**Conclusion**',
    irac.conclusion,
    '',
    sourceTag,
  ];
  return lines.join('\n');
}

// --- LLM-generated analysis and conclusion (Claude 3.5 Sonnet) ---

const IRAC_LLM_MODEL = 'claude-sonnet-4-5-20250929';

async function generateIRACAnalysisAndConclusion(
  issue: string,
  ruleText: string,
  question: string,
  chunks: HandbookChunk[]
): Promise<{ analysis: string; conclusion: string }> {
  const fallbackConclusion = `Therefore, the accounting treatment is supported by ${chunks[0]?.framework ?? 'FASB'} ${chunks[0]?.citation ?? 'FASB ASC (General)'}.`;
  if (!process.env.ANTHROPIC_API_KEY && !process.env.OPENAI_API_KEY && !process.env.MISTRAL_API_KEY) {
    return {
      analysis: `Applying the foregoing guidance to the facts: ${question.trim().slice(0, 200)}. The treatment is consistent with the authoritative literature cited.`,
      conclusion: fallbackConclusion,
    };
  }

  const citationsBlock = chunks.length
    ? chunks
        .map((c) => `- ${c.framework} ${c.citation}${c.section ? ` (${c.section})` : ''}: ${c.text}`)
        .join('\n')
    : 'No specific authority chunks. Apply GAAP/IFRS as appropriate.';

  const system = `You are an expert in GAAP/IFRS. Write IRAC-style Analysis and Conclusion for an accounting justification. 
  Cite the specific FASB ASC or IFRS codifications from the provided authority chunks. Use the exact citation strings (e.g. "FASB ASC 606-10-25-1", "IAS 1.54") when referencing the literature.
  Output exactly two short paragraphs: first "Analysis:", then "Conclusion:". Do not include section headers in the text; just the paragraphs.`;
  const prompt = `Issue: ${issue}\n\nRule (from authority): ${ruleText}\n\nRelevant authority chunks:\n${citationsBlock}\n\nUser question / facts: ${question.slice(0, 500)}\n\nWrite Analysis (apply the rule to the facts; cite the codifications above) and Conclusion (state whether the treatment is supported and by which citation).`;

  const text = await generateText({
    model: IRAC_LLM_MODEL,
    maxTokens: 1024,
    system,
    prompt,
  });

  let analysis = text;
  let conclusion = '';
  const conclusionMatch = text.match(/\bConclusion:?\s*([\s\S]*)/i);
  if (conclusionMatch) {
    conclusion = conclusionMatch[1].trim();
    analysis = text.slice(0, text.indexOf(conclusionMatch[0])).replace(/Analysis:?\s*/i, '').trim();
  }
  if (!conclusion) {
    const lastPara = text.split(/\n\n+/).pop() ?? text;
    conclusion = lastPara.trim();
    analysis = text.slice(0, text.lastIndexOf(lastPara)).replace(/Analysis:?\s*/i, '').trim();
  }
  if (!analysis) analysis = text;
  if (!conclusion) conclusion = fallbackConclusion;

  return { analysis, conclusion };
}

// --- RAG-backed justification ---

export interface JustifyOptions {
  ragStore?: JustificationRAGStore;
  framework?: 'FASB' | 'IFRS';
}

/**
 * Produce a justification using RAG (FASB/IFRS handbook). Returns IRAC + [Source] citation.
 * Analysis and conclusion are generated by Claude 3.5 Sonnet, citing the specific codifications from RAG chunks.
 */
export async function justifyWithRAG(
  question: string,
  options?: JustifyOptions
): Promise<JustificationResponse> {
  const store = options?.ragStore ?? getDefaultRAGStore();
  const rag: RAGResult = await store.query(question, {
    topK: 3,
    framework: options?.framework,
  });
  const chunks = rag.chunks;
  const chunk = chunks[0];
  const citation = chunk ? chunk.citation : 'FASB ASC (General)';
  const ruleText = chunk ? chunk.text : 'Relevant GAAP or IFRS applies as determined by management and auditors.';

  const issue = normalizeIssue(question);
  const rule = ruleText;

  const { analysis, conclusion } = await generateIRACAnalysisAndConclusion(issue, rule, question, chunks);

  const sourceTag = `${SOURCE_TAG_PREFIX}${chunk?.framework ?? 'FASB'} ${citation}${SOURCE_TAG_SUFFIX}`;

  const irac: IRACJustification = {
    issue,
    rule,
    analysis,
    conclusion,
    source: `${chunk?.framework ?? 'FASB'} ${citation}`,
  };

  const formatted = formatJustificationText(irac, sourceTag);

  const out: JustificationResponse = {
    irac,
    sourceTag,
    formatted,
  };

  storeJustification(question, out);
  return out;
}

function normalizeIssue(q: string): string {
  const t = q.trim();
  if (t.length === 0) return 'Whether the accounting treatment is appropriate under GAAP/IFRS.';
  if (t.length > 300) return t.slice(0, 297) + '...';
  return t;
}

function storeJustification(question: string, response: JustificationResponse): void {
  justificationStore.push({
    id: `j-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
    question,
    response,
    timestamp: new Date().toISOString(),
  });
}

// --- Export Audit Defense ---

export interface ExportAuditDefenseOptions {
  periodStart: string;
  periodEnd: string;
  title?: string;
  entityName?: string;
}

/**
 * Get all justifications in a period for Export Audit Defense.
 */
export function getJustificationsForPeriod(periodStart: string, periodEnd: string): StoredJustification[] {
  const start = new Date(periodStart).getTime();
  const end = new Date(periodEnd).getTime();
  return justificationStore.filter((j) => {
    const t = new Date(j.timestamp).getTime();
    return t >= start && t <= end;
  });
}

/**
 * Build Audit Defense summary (HTML) for a period. Used for PDF export.
 */
export function buildAuditDefenseSummary(options: ExportAuditDefenseOptions): {
  html: string;
  justifications: StoredJustification[];
} {
  const { periodStart, periodEnd, title = 'Audit Defense — Justifications', entityName = 'Entity' } = options;
  const justifications = getJustificationsForPeriod(periodStart, periodEnd);

  const sections = justifications
    .map(
      (j, i) => `
    <div class="justification" style="margin-bottom: 2rem; page-break-inside: avoid;">
      <h3 style="font-size: 1rem; margin-bottom: 0.5rem;">${i + 1}. ${escapeHtml(j.question.slice(0, 100))}${j.question.length > 100 ? '...' : ''}</h3>
      <p style="font-size: 0.75rem; color: #666;">${escapeHtml(j.timestamp)}</p>
      <div style="margin-left: 0.5rem;">
        <p><strong>Issue:</strong> ${escapeHtml(j.response.irac.issue)}</p>
        <p><strong>Rule:</strong> ${escapeHtml(j.response.irac.rule)}</p>
        <p><strong>Analysis:</strong> ${escapeHtml(j.response.irac.analysis)}</p>
        <p><strong>Conclusion:</strong> ${escapeHtml(j.response.irac.conclusion)}</p>
        <p><strong>Citation:</strong> ${escapeHtml(j.response.sourceTag)}</p>
      </div>
    </div>
  `
    )
    .join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: Georgia, serif; font-size: 11pt; line-height: 1.5; max-width: 800px; margin: 2rem auto; padding: 0 1rem; }
    h1 { font-size: 1.5rem; border-bottom: 1px solid #333; padding-bottom: 0.5rem; }
    h2 { font-size: 1.2rem; margin-top: 1.5rem; }
    .meta { color: #666; font-size: 0.9rem; margin-bottom: 1.5rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">
    <p><strong>Entity:</strong> ${escapeHtml(entityName)}</p>
    <p><strong>Period:</strong> ${escapeHtml(periodStart)} to ${escapeHtml(periodEnd)}</p>
    <p><strong>Report generated:</strong> ${new Date().toISOString()}</p>
  </div>
  <h2>Justifications (IRAC)</h2>
  ${sections || '<p>No justifications recorded for this period.</p>'}
</body>
</html>`;

  return { html, justifications };
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Export Audit Defense: generate PDF buffer for justifications in a period.
 * Uses dynamic import of pdf-lib or returns HTML for client-side PDF; see route for actual PDF generation.
 */
export async function exportAuditDefensePDF(options: ExportAuditDefenseOptions): Promise<Buffer> {
  const { html } = buildAuditDefenseSummary(options);
  // Use a simple PDF library. pdf-lib doesn't do HTML; we use puppeteer or jsPDF in browser, or a Node HTML-to-PDF.
  // For Node without puppeteer: return HTML as fallback and let route set Content-Type or use pdf-lib to build simple PDF.
  try {
    const { createPdfFromHtml } = await import('./pdf_export.js');
    return await createPdfFromHtml(html);
  } catch {
    // Fallback: return HTML as buffer so caller can serve as HTML or use external service for PDF
    return Buffer.from(html, 'utf-8');
  }
}

/**
 * Register a justification with period for audit defense (call from chat).
 */
export function registerJustificationForPeriod(
  question: string,
  response: JustificationResponse,
  periodStart?: string,
  periodEnd?: string
): void {
  justificationStore.push({
    id: `j-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
    question,
    response,
    timestamp: new Date().toISOString(),
    periodStart,
    periodEnd,
  });
}
