/**
 * Startup validation: checks all prerequisites before server.listen().
 * On any fatal failure: log clear error, exit with code 1.
 */

import { mkdir } from 'fs/promises';
import { join } from 'path';
import pg from 'pg';
import { getMode, getAppMode } from './lib/runtime_mode.js';
import { getSecurityProfile } from './security/security_profile.js';
import { isSigningConfigured, isKeysAutoGenerated, validateSigningKeysProduceValidSignature } from './lib/cert_signing.js';
import { isDbConfigured, isAiBoundaryDbRolesEnabled } from './db/index.js';
import { runMigrations } from './db/migrate.js';

const STORAGE_BASE = process.env.STORAGE_LOCAL_BASE_PATH ?? join(process.cwd(), 'storage');

function isTest(): boolean {
  return process.env.NODE_ENV === 'test';
}

/** Validation result for testability. */
export interface StartupValidationResult {
  ok: boolean;
  errors: string[];
  warnings: string[];
}

/**
 * Pure env checks (no DB, no FS). Testable with mocked process.env.
 */
export function validateEnv(): StartupValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  const profile = getSecurityProfile(process.env);
  const isStrictMode = profile.appMode === 'prod' || profile.appMode === 'staging' || profile.appMode === 'demo';

  if (!process.env.DATABASE_URL?.trim()) {
    errors.push('DATABASE_URL is not set. Set it in .env or environment.');
  }

  if (profile.authRequired && !process.env.JWT_SECRET?.trim()) {
    errors.push('JWT_SECRET is required when auth is enforced.');
  }

  if (isStrictMode) {
    if (process.env.REQUIRE_AUTH === 'false') {
      errors.push(`MODE=${profile.appMode} requires REQUIRE_AUTH=true.`);
    }
    if (process.env.ALLOW_IMBALANCED_DRAFT_EXPORT === 'true') {
      errors.push(`MODE=${profile.appMode} requires ALLOW_IMBALANCED_DRAFT_EXPORT=false.`);
    }
    if (process.env.ALLOW_LEGACY_CERTIFIED_SOURCE === 'true') {
      errors.push(`MODE=${profile.appMode} requires ALLOW_LEGACY_CERTIFIED_SOURCE=false.`);
    }
    if (process.env.AI_MOCK === 'true' || process.env.AI_MOCK_CLASSIFIER === 'true' || process.env.AI_MOCK_ADVISOR === 'true') {
      errors.push(`MODE=${profile.appMode} requires AI_MOCK=false (and AI_MOCK_CLASSIFIER, AI_MOCK_ADVISOR).`);
    }
    if (process.env.AI_BOUNDARY_DB_ROLES === 'true') {
      const hasAiUrl = Boolean(process.env.DATABASE_AI_URL?.trim());
      const hasAiUser = Boolean(process.env.AI_DB_USER?.trim());
      if (!hasAiUrl && !hasAiUser) {
        errors.push(
          'AI_BOUNDARY_DB_ROLES=true requires DATABASE_AI_URL or AI_DB_USER (and AI_DB_PASSWORD for BYOD).'
        );
      }
    }
  }

  if (profile.appMode === 'prod' || profile.appMode === 'staging') {
    const PLACEHOLDER_JWT_SECRETS = [
      'secret',
      'jwt-secret',
      'changeme',
      'dev-secret',
      'dev-secret-change-in-prod',
      'dev-secret-change-in-production',
    ];
    const jwtSecret = process.env.JWT_SECRET?.trim();
    const isPlaceholder = !jwtSecret || PLACEHOLDER_JWT_SECRETS.includes(jwtSecret);
    if (isPlaceholder) {
      errors.push(
        'Production requires a real JWT_SECRET (not a placeholder like "secret", "changeme", "dev-secret-change-in-prod"). Set JWT_SECRET in the environment.'
      );
    }
    const priv = process.env.CERT_SIGNING_PRIVATE_KEY?.trim();
    const pub = process.env.CERT_SIGNING_PUBLIC_KEY?.trim();
    if (!priv || !pub) {
      errors.push(
        'FATAL: Ed25519 signing keys required in production. Run npx tsx src/crypto/keygen.ts to generate.'
      );
    }
  }

  return {
    ok: errors.length === 0,
    errors,
    warnings,
  };
}

/**
 * Check database connection. Creates temp pool, does not use global pool.
 */
async function checkDatabaseConnection(): Promise<void> {
  const url = process.env.DATABASE_URL?.trim();
  if (!url) return;

  const pool = new pg.Pool({ connectionString: url, max: 1 });
  try {
    await pool.query('SELECT 1');
  } finally {
    await pool.end();
  }
}

/**
 * Ensure storage base path exists or can be created.
 */
async function checkStoragePath(): Promise<void> {
  await mkdir(STORAGE_BASE, { recursive: true });
}

/**
 * Full startup validation. Throws on fatal error; warnings are logged only.
 * Call before server.listen().
 */
export async function runStartupValidation(): Promise<void> {
  if (isTest()) return;

  const envResult = validateEnv();
  if (!envResult.ok) {
    for (const e of envResult.errors) {
      console.error(`[FATAL] ${e}`);
    }
    console.error('[FATAL] Startup validation failed. Refusing to start.');
    process.exit(1);
  }

  if (!isDbConfigured()) {
    console.error('[FATAL] DATABASE_URL is not set. Refusing to start.');
    process.exit(1);
  }

  try {
    await checkDatabaseConnection();
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[FATAL] Cannot connect to database: ${msg}`);
    process.exit(1);
  }

  try {
    await runMigrations();
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[FATAL] Migrations failed: ${msg}`);
    process.exit(1);
  }

  try {
    await checkStoragePath();
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[FATAL] Storage path cannot be created: ${STORAGE_BASE}. ${msg}`);
    process.exit(1);
  }

  if (getMode() === 'prod' || getMode() === 'staging') {
    try {
      validateSigningKeysProduceValidSignature();
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[FATAL] Ed25519 signing keys validation failed: ${msg}`);
      process.exit(1);
    }
  }

  if ((getMode() === 'prod' || getMode() === 'staging' || getMode() === 'demo') && isAiBoundaryDbRolesEnabled()) {
    try {
      await validateAiBoundaryGrants();
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[FATAL] AI boundary DB grants validation failed: ${msg}`);
      process.exit(1);
    }
  }
}

/**
 * Verify required roles and grants for AI boundary (when AI_BOUNDARY_DB_ROLES=true).
 * Fails if core/ai/audit schemas exist but roles are missing or ai_writer can write to core.
 */
async function validateAiBoundaryGrants(): Promise<void> {
  const url = process.env.DATABASE_URL?.trim();
  if (!url) return;

  const pool = new pg.Pool({ connectionString: url, max: 1 });
  try {
    const schemaCheck = await pool.query<{ n: string }>(
      `SELECT count(*)::text AS n FROM information_schema.schemata WHERE schema_name IN ('core','ai','audit')`
    );
    const schemaCount = parseInt(schemaCheck.rows[0]?.n ?? '0', 10);
    if (schemaCount < 3) return;

    const roles = await pool.query<{ rolname: string }>(
      `SELECT rolname FROM pg_roles WHERE rolname IN ('core_writer','ai_writer','auditor_reader')`
    );
    const found = new Set(roles.rows.map((r) => r.rolname));
    if (!found.has('core_writer') || !found.has('ai_writer') || !found.has('auditor_reader')) {
      throw new Error(
        'AI boundary: core_writer, ai_writer, auditor_reader roles required. Run migration 093 (npx tsx src/db/migrate.ts --tenant).'
      );
    }

    const client = await pool.connect();
    try {
      await client.query('SET ROLE ai_writer');
      try {
        await client.query(
          `INSERT INTO core.period_trial_balance (tenant_id, period_label, entries, created_at, updated_at)
           VALUES ($1, $2, '[]'::jsonb, NOW(), NOW())`,
          [`grant-check-${Date.now()}`, '2025-01']
        );
        throw new Error(
          'AI boundary: ai_writer must NOT be able to INSERT into core tables. Grant configuration is incorrect.'
        );
      } catch (e: unknown) {
        const err = e as { code?: string };
        if (err?.code === '42501') return;
        throw e;
      }
    } finally {
      await client.query('RESET ROLE');
      client.release();
    }
  } finally {
    await pool.end();
  }
}

/** Print startup banner: mode, auth, Ed25519, port, DB status. */
export function printStartupBanner(): void {
  const mode = getMode();
  const modeLabel = mode === 'prod' ? 'PRODUCTION' : mode === 'staging' ? 'STAGING' : mode === 'demo' ? 'DEMO' : 'DEVELOPMENT';
  const p = getSecurityProfile(process.env);
  const authEnforced = p.appMode === 'prod' || p.appMode === 'staging' || p.appMode === 'demo' ? 'ENFORCED' : p.authRequired ? 'ENFORCED' : 'optional';
  const ed25519Status = isSigningConfigured()
    ? isKeysAutoGenerated()
      ? 'AUTO'
      : 'ENV'
    : 'none';
  const dbStatus = isDbConfigured() ? 'Connected' : 'Not configured';
  const port = process.env.PORT ?? '3001';

  console.log('\n┌─────────────────────────────────────────────┐');
  console.log('│  CPACFA Financial Integrity Platform         │');
  console.log(`│  Mode: ${modeLabel.padEnd(10)} | Auth: ${String(authEnforced).padEnd(8)} | Keys: ${String(ed25519Status).padEnd(4)}   │`);
  console.log(`│  Port: ${port.padEnd(6)} | DB: ${dbStatus.padEnd(22)} │`);
  console.log('└─────────────────────────────────────────────┘\n');
}
