/**
 * Minimal Claude adapter for Sovereign CPA Engine. Uses existing LLM provider.
 * No secrets logged; timeout supported via Promise.race.
 * When AI_MOCK=true, returns deterministic valid JSON per pillar (justifier | shadow_auditor).
 * Shadow mock: AI_SHADOW_SEVERITY=ok|warn|block, AI_SHADOW_FINDINGS_JSON optional.
 */

import { generateText } from '../../llm/provider.js';
import { aiMock, aiMockClassifier, aiMockAdvisor } from '../../lib/runtime_mode.js';
import { JUSTIFIER_PROMPT_VERSION } from '../prompts/justifier.prompt.js';
import { SHADOW_AUDITOR_PROMPT_VERSION } from '../prompts/shadow_auditor.prompt.js';
import { CLASSIFIER_PROMPT_VERSION } from '../prompts/classifier.prompt.js';
import { ADVISOR_PROMPT_VERSION } from '../prompts/advisor.prompt.js';

export interface ClaudeAdapterInput {
  model: string;
  systemPrompt: string;
  userPrompt: string;
  timeoutMs: number;
  /** When AI_MOCK=true, used to select mock response (justifier | shadow_auditor). */
  pillar?: string;
}

export interface ClaudeAdapterOutput {
  ok: boolean;
  rawText?: string;
  error?: string;
}

const MOCK_JUSTIFIER_JSON = JSON.stringify({
  prompt_version: JUSTIFIER_PROMPT_VERSION,
  irac: {
    issue: 'Whether the journal entry is appropriately supported by documentation and policy.',
    rule: 'Reclassification and accrual principles apply; amounts are as provided.',
    analysis: 'Facts were reviewed. No amounts were computed or changed by AI.',
    conclusion: 'The entry is documented for audit. Memo generated by Justifier (mock).',
  },
  memo_markdown:
    '**Issue** Whether the journal entry is appropriately supported.\n**Rule** Reclassification/accrual principles.\n**Analysis** Facts reviewed; no AI math.\n**Conclusion** Documented for audit (mock).',
  rule_ids: ['no_ai_math', 'reclassification', 'documentation'],
  facts_used: ['jeId', 'lines'],
});

function getMockShadowAuditorJson(): string {
  const severity = (process.env.AI_SHADOW_SEVERITY ?? 'ok') as 'ok' | 'warn' | 'block';
  let findings: Array<{ code: string; message: string; rule_ids: string[]; refs: string[] }> = [];
  try {
    if (process.env.AI_SHADOW_FINDINGS_JSON) {
      const parsed = JSON.parse(process.env.AI_SHADOW_FINDINGS_JSON);
      if (Array.isArray(parsed)) findings = parsed;
    }
  } catch {
    // ignore invalid JSON
  }
  if (findings.length === 0 && severity !== 'ok') {
    findings = [{ code: 'MOCK_FINDING', message: 'Mock shadow audit finding.', rule_ids: [], refs: [] }];
  }
  const confidence = severity === 'ok' ? 1 : severity === 'warn' ? 0.7 : 0.9;
  return JSON.stringify({
    prompt_version: SHADOW_AUDITOR_PROMPT_VERSION,
    severity,
    confidence,
    findings,
  });
}

function getMockClassifierJson(): string {
  return JSON.stringify({
    prompt_version: CLASSIFIER_PROMPT_VERSION,
    results: [
      {
        source_id: 'row-0',
        object_type: 'expense',
        fs_placement: 'pnl.expense',
        suggested_accounts: ['Operating Expense'],
        rule_tags: ['expense_in_period'],
        missing_inputs: [],
        confidence: 0.85,
      },
      {
        source_id: 'row-1',
        object_type: 'revenue',
        fs_placement: 'pnl.revenue',
        suggested_accounts: ['Revenue'],
        rule_tags: ['revenue_performance'],
        missing_inputs: [],
        confidence: 0.85,
      },
    ],
  });
}

function getMockAdvisorJson(): string {
  return JSON.stringify({
    prompt_version: ADVISOR_PROMPT_VERSION,
    proposals: [
      {
        proposal_id: 'adv-mock-1',
        type: 'reclass',
        rationale: 'Mock reclass suggestion; amounts from source only.',
        rule_ids: ['reclass_hint'],
        confidence: 0.8,
        requires_human_confirmation: true,
        lines: [
          {
            dr_account_key: 'Operating Expense',
            cr_account_key: 'Prepaid',
            amountProvenance: 'SOURCE_LINE_AMOUNT',
            sourceRef: { tbRowId: 'row-0' },
            note: 'Mock; human must confirm.',
          },
        ],
        missing_inputs: [],
      },
    ],
  });
}

export async function callClaude(input: ClaudeAdapterInput): Promise<ClaudeAdapterOutput> {
  if (aiMockClassifier() && input.pillar === 'classifier') {
    return { ok: true, rawText: getMockClassifierJson() };
  }
  if (aiMockAdvisor() && input.pillar === 'advisor') {
    return { ok: true, rawText: getMockAdvisorJson() };
  }
  if (aiMock()) {
    const rawText =
      input.pillar === 'shadow_auditor' ? getMockShadowAuditorJson() : MOCK_JUSTIFIER_JSON;
    return { ok: true, rawText };
  }

  const { model, systemPrompt, userPrompt, timeoutMs } = input;

  const timeoutPromise = new Promise<never>((_, reject) => {
    setTimeout(() => reject(new Error('AI_TIMEOUT')), timeoutMs);
  });

  try {
    const textPromise = generateText({
      model,
      maxTokens: 2048,
      system: systemPrompt,
      prompt: userPrompt,
    });
    const rawText = await Promise.race([textPromise, timeoutPromise]);
    return { ok: true, rawText: rawText?.trim() ?? '' };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const isKeyMissing =
      /ANTHROPIC_API_KEY|OPENAI_API_KEY|MISTRAL_API_KEY|is not set/i.test(message);
    const error = isKeyMissing ? 'API_KEY_MISSING' : message;
    return { ok: false, error };
  }
}
