/**
 * Close routes aggregate: mounts all close sub-routers at /api/close (no path prefix here).
 * Each sub-router defines full paths (e.g. /adjustments, /period-lock) so combined paths stay identical.
 */

import { Router } from 'express';
import closeJeAccrualsRouter from './close_je_accruals.js';
import closeChecklistRouter from './close_checklist.js';
import closePeriodRouter from './close_period.js';
import closeReconciliationRouter from './close_reconciliation.js';
import closeControlsRouter from './close_controls.js';
import closeMaterialityDisclosureRouter from './close_materiality_disclosure.js';
import closeSignoffReadinessRouter from './close_signoff_readiness.js';
// QUARANTINED — Summary/reporting routes not in MVP architecture
// import closeOnePagerExceptionsRouter from './close_one_pager_exceptions.js';
// import closePackageRouter from './close_package.js';
import closeAdjustmentsRouter from './close_adjustments.js';
import closeClosingEntriesRouter from './close_closing_entries.js';
import closeAuditLogRouter from './close_audit_log.js';
import closeSegregationRouter from './close_segregation.js';
import closeTaskAssignRouter from './close_task_assign.js';
import closeSessionsRouter from './close_sessions.js';
import closeIssuesRouter from './close_issues.js';
import closeDecisionRecordsRouter from './close_decision_records.js';
import closeReconRunsRouter from './close_recon_runs.js';
import closeJournalEntriesRouter from './close_journal_entries.js';
import closeEvidencePolicyRouter from './close_evidence_policy.js';
import closeReconRequirementsRouter from './close_recon_requirements.js';
import closePeriodReconciliationsRouter from './close_period_reconciliations.js';
import closeAjeTemplatesRouter from './close_aje_templates.js';
import closeVarianceAnalysisRouter from './close_variance_analysis.js';
import closeIntercompanyRouter from './close_intercompany.js';
import closeReportPackRouter from './close_report_pack.js';
import closeInvestigationRouter from './close_investigation.js';
import closeSuggestionsRouter from './close_suggestions.js';
import closeFixedAssetsRouter from './close_fixed_assets.js';
import closeDeferredTaxRouter from './close_deferred_tax.js';
import closeStockCompensationRouter from './close_stock_compensation.js';
import closeImpairmentRouter from './close_impairment.js';
import closeSegmentsRouter from './close_segments.js';
import closeBoardPackageRouter from './close_board_package.js';
import closeExchangeRatesRouter from './close_exchange_rates.js';
import closeConsolidationConfigRouter from './close_consolidation_config.js';
import closeFxTranslationConfigRouter from './close_fx_translation_config.js';
import closeGlHealthRouter from './close_gl_health.js';
import closeGlReplaceRouter from './close_gl_replace.js';
import closeReconSourceRouter from './close_recon_source.js';
import closeBudgetRouter from './close_budget.js';
import closeEbitdaBridgeRouter from './close_ebitda_bridge.js';
import closePeReportingRouter from './close_pe_reporting.js';
import closeExcelExportRouter from './close_excel_export.js';
import closeAuditDataRouter from './close_audit_data.js';
import closeAccountAnalysisRouter from './close_account_analysis.js';
import closeSubsequentEventsRouter from './close_subsequent_events.js';
import closeDebtAccrualRouter from './close_debt_accrual.js';
import closePayrollAccrualRouter from './close_payroll_accrual.js';
import closePrepaidRouter from './close_prepaid.js';
import closeArAgingRouter from './close_ar_aging.js';
import closeApAgingRouter from './close_ap_aging.js';
import closeInventoryReserveRouter from './close_inventory_reserve.js';
import closeLeasesRouter from './close_leases.js';
import closeAccountingProfilesRouter from './close_accounting_profiles.js';
import closeRunbooksRouter from './close_runbooks.js';
import closeAccountingMemoryRouter from './close_accounting_memory.js';
import { createBankTransactionRoutes } from './close_bank_transactions.js';
import { getTenantPool } from '../../db/index.js';

const router = Router();
const bankTransactionRouter = createBankTransactionRoutes(getTenantPool);
router.use(closeAccountingProfilesRouter);
router.use(closeRunbooksRouter);
router.use(closeAccountingMemoryRouter);
router.use(closeJeAccrualsRouter);
router.use(closeSessionsRouter);
router.use(closeIssuesRouter);
router.use(closeDecisionRecordsRouter);
router.use(closeReconRunsRouter);
router.use(closeReconRequirementsRouter);
router.use(closePeriodReconciliationsRouter);
router.use(closeAjeTemplatesRouter);
router.use(closeVarianceAnalysisRouter);
router.use(closeJournalEntriesRouter);
router.use(closeEvidencePolicyRouter);
router.use(closeChecklistRouter);
router.use(closePeriodRouter);
router.use(closeReconciliationRouter);
router.use(closeControlsRouter);
router.use(closeMaterialityDisclosureRouter);
router.use(closeSignoffReadinessRouter);
// QUARANTINED — Summary/reporting routes not in MVP architecture
// router.use(closeOnePagerExceptionsRouter);
// router.use(closePackageRouter);
router.use(closeAdjustmentsRouter);
router.use(closeClosingEntriesRouter);
router.use(closeAuditLogRouter);
router.use(closeSegregationRouter);
router.use(closeTaskAssignRouter);
router.use(closeIntercompanyRouter);
router.use(closeReportPackRouter);
router.use(closeInvestigationRouter);
router.use(closeSuggestionsRouter);
router.use(closeFixedAssetsRouter);
router.use(closeDeferredTaxRouter);
router.use(closeStockCompensationRouter);
router.use(closeImpairmentRouter);
router.use(closeSegmentsRouter);
router.use(closeBoardPackageRouter);
router.use(closeExchangeRatesRouter);
router.use(closeConsolidationConfigRouter);
router.use(closeFxTranslationConfigRouter);
router.use(closeGlHealthRouter);
router.use(closeGlReplaceRouter);
router.use(closeReconSourceRouter);
router.use(closeBudgetRouter);
router.use(closeEbitdaBridgeRouter);
router.use(closePeReportingRouter);
router.use(closeExcelExportRouter);
router.use(closeAuditDataRouter);
router.use(closeAccountAnalysisRouter);
router.use(closeSubsequentEventsRouter);
router.use(closeDebtAccrualRouter);
router.use(closePayrollAccrualRouter);
router.use(closePrepaidRouter);
router.use(closeArAgingRouter);
router.use(closeApAgingRouter);
router.use(closeInventoryReserveRouter);
router.use(closeLeasesRouter);
router.use(bankTransactionRouter);

export default router;
